=== vdgg/nusuth/src/com/azoft/nusuth/deployment/cluster.dtd
<!ELEMENT cluster (name, allow-hosts, manager, web-inf-storage, logger, access-config, component*, host*)>
<!ELEMENT name (#PCDATA)>
<!-- comma-separated list -->
<!ELEMENT allow-hosts (#PCDATA)>
<!ELEMENT manager (port, auth-key, user-name, password)>
<!ELEMENT web-inf-storage (#PCDATA)>
<!ELEMENT access-config (#PCDATA)>
<!-- defines component section -->
<!ELEMENT component (name, type, host-name, port)>
<!-- may be "container", "deployer" or "distributor" -->
<!ELEMENT type (#PCDATA)>
<!ELEMENT host-name (#PCDATA)>
<!-- integer value -->
<!ELEMENT port (#PCDATA)>
<!-- defines logging settings -->
<!ELEMENT logger (level, location?, config?)>
<!-- specifies logging level. There are four levels are available:
    DEBUG, INFO, WARN and ERROR -->
<!ELEMENT level (#PCDATA)>
<!-- specifies directory where log files located -->
<!ELEMENT location (#PCDATA)>
<!-- Specifies alternative config file location for logging system.
    We are using log4j logging component. Please refer to www.log4j.org for
    more information -->
<!ELEMENT config (#PCDATA)>
<!ELEMENT host (id, doc-base, context*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT doc-base (#PCDATA)>
<!ELEMENT context (url, protocol, is-running, container*, location)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT is-running (#PCDATA)>
<!ELEMENT container (#PCDATA)>
<!ELEMENT user-name (#PCDATA)>
<!ELEMENT hash-password (#PCDATA)>
<!ATTLIST name
	id ID #IMPLIED
>
<!ATTLIST allow-hosts
	id ID #IMPLIED
>
<!ATTLIST web-inf-storage
	id ID #IMPLIED
>
<!ATTLIST manager
	id ID #IMPLIED
>
<!ATTLIST access-config
	id ID #IMPLIED
>
<!ATTLIST component
	id ID #IMPLIED
>
<!ATTLIST type
	id ID #IMPLIED
>
<!ATTLIST host-name
	id ID #IMPLIED
>
<!ATTLIST port
	id ID #IMPLIED
>
<!ATTLIST logger
	id ID #IMPLIED
>
<!ATTLIST level
	id ID #IMPLIED
>
<!ATTLIST location
	id ID #IMPLIED
>
<!ATTLIST config
	id ID #IMPLIED
>
<!ATTLIST host
	id ID #IMPLIED
>
<!ATTLIST id
	id ID #IMPLIED
>
<!ATTLIST context
	id ID #IMPLIED
>
<!ATTLIST url
	id ID #IMPLIED
>
<!ATTLIST protocol
	id ID #IMPLIED
>
<!ATTLIST is-running
	id ID #IMPLIED
>
<!ATTLIST container
	id ID #IMPLIED
>

=== vdgg/nusuth/admin/cluster.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE cluster SYSTEM "cluster.dtd">

<cluster>
  <name>Cluster Manager</name>
  <allow-hosts>127.0.0.1</allow-hosts>
  <manager>
    <port>9000</port>
    <auth-key>1234567890</auth-key>
  </manager>
  <web-inf-storage>\tmp\cluster</web-inf-storage>
  <logger>
    <level>DEBUG</level>
  </logger>
  <access-config>../admin/security.xml</access-config>
  <component>
    <name>second</name>
    <type>container</type>
    <host-name>localhost</host-name>
    <port>9202</port>
  </component>
  <component>
    <name>first distr</name>
    <type>distributor</type>
    <host-name>localhost</host-name>
    <port>9101</port>
  </component>
  <component>
    <name>first</name>
    <type>container</type>
    <host-name>localhost</host-name>
    <port>9201</port>
  </component>
  <host>
    <id>*</id>
    <doc-base>z:\jerry\webapps</doc-base>
    <context>
      <url>/jazz</url>
      <protocol>http</protocol>
      <is-running>true</is-running>
      <container>second</container>
      <container>first</container>
      <location>/jazz</location>
    </context>
    <context>
      <url>/</url>
      <protocol>http</protocol>
      <is-running>true</is-running>
      <container>second</container>
      <container>first</container>
      <location>/jtest</location>
    </context>
  </host>
</cluster>

=== vdgg/nusuth/src/com/azoft/nusuth/deployment/cluster.xml
<?xml version="1.0"?>
<!DOCTYPE cluster SYSTEM "cluster.dtd">
<cluster>

  <name></name>
  <allow-hosts></allow-hosts>

  <manager>
    <port></port>
    <auth-key></auth-key>
  </manager>

  <web-inf-storage></web-inf-storage>
  <logger>
    <level></level>
  </logger>
  <access-config></access-config>

</cluster>
